# Generated by Django 5.0.4 on 2024-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MarketDataApp', '0002_delete_utente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('asset', models.CharField(max_length=100)),
                ('dataInizio', models.DateField()),
                ('dataFine', models.DateField()),
            ],
        ),
    ]
