# Generated by Django 5.0.4 on 2024-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketDataApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
